### PR TITLE
Upgrade svelte

### PR DESCRIPTION
**Pull request by benjavicente**
This PR upgrades Svelte to use `svelte:element`  in the Render component, removing the monstrosity that was needed to use the `as={element}` prop.

> pd: thank you for the awesome port of the Headless UI 🚀

### CODE REVIEW

**Comment by benjavicente** [comment]
Some other notes:
- [`isValidElement`](https://github.com/rgossiaux/svelte-headlessui/blob/8bc5fabdd953274e5a4cd9ff4e148eb6948c12ab/src/lib/internal/elements/index.ts#L47) probably should be changed to somethong that validates if the `as` prop is a string or a component, [like the official library](https://github.com/tailwindlabs/headlessui/blob/3e19aa5c97f98aaa4106db3f8a2c9f9fb1ce8386/packages/%40headlessui-vue/src/utils/render.ts#L147-L153).
- There seems to be missing tests in of `Render.svelte` because svelte componentes are not tested as a `as` prop.

**Review by rgossiaux — CHANGES_REQUESTED** [review]
Thanks!

You need to update the `peerDependencies` to 3.47.0 as well, since users will need that for this to work. For that reason I haven't rushed to implementing this, so I'll probably merge your PR in a couple weeks (also gives us a little more time for bugs in svelte:element to be found).

**Comment by rgossiaux** [comment]
Oh, and yes, the TS types can be simplified now, as you mentioned--we should delete the hardcoded list of elements.

**Comment by rgossiaux** [comment]
Thanks for this PR @benjavicente ! I know I'm responding to it a little late :) I've switched over to <svelte:element> in the `next` branch (see #96) so I'm going to close this now. I like your changes to `elements.ts` but for some reason they make `svelte-check` take about 10x longer so I'm not incorporating them for now.

**Pull request closed without merging**
