### PR TITLE
config.kit.target is no longer required, and should be removed

### PR DESCRIPTION
**Pull request by twobitunicorn**

### CODE REVIEW

**Comment by rgossiaux** [comment]
This may have been removed in a recent version of SvelteKit, but it's still there in the version that's pinned in `package-lock.json`. Did you run into this yourself? / Where did this PR come from?

**Comment by twobitunicorn** [comment]
So this is interesting.  I use `pnpm` and with `pnpm` it seems to hit this error.  But with `npm` it doesn't.  Seems you have to pass the flag `--lockfile-only` to `pnpm` to have it respect the version that is pinned.  My bad!  So use to using `pnpm`.

**Comment by twobitunicorn** [comment]
@rgossiaux should I just close the pull?

**Comment by rgossiaux** [comment]
Yeah, I'll make this change if/when I end up upgrading the Kit version, but for now I'd like to leave it as it is. I don't want to have to worry about keeping up with the breaking changes in Kit. Thanks for the PR, though!

**Pull request closed without merging**
